version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: mysql
      volumes:
        - ./mysql:/var/lib/mysql
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpMyAdminVueForm
      ports:
       - '8090:80'
      environment:
        PMA_HOST: 'db'
