version: '3.3'
services:
   ap:
      image: httpd:latest
      container_name: apache
      volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      ports:
       - 8080:80
   db:
      image: mysql:latest
      container_name: mysqlcontainer
      volumes:
      - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
       - 3306:3306
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: adminphp
      ports:
       - 8090:80
      environment:
        PMA_HOST: db
   jdk:
      restart: on-failure
      depends_on:
       - db
      image: neo3kk/comeencasa:latest
      container_name: jre
      stdin_open: true # docker run -i
      tty: true # docker run -t
      ports:
       - 5000:5000
      environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer:3306/hibernate?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
